### ISSUE TITLE
get_who_mr returns NA

### ISSUE THREAD

**Issue by gloriamacia** [cran/rgho#1]
Trying to retrieve the latest data available (2021) from WHO in Canada. Mean age is 58 years, sex is female. 
This is my code, following the docs: 

```
age = 58
sex = 0
country = "CAN" #Canada
sex_cat = ifelse(sex == 0, "FMLE", "MLE")
mr = get_who_mr(age, sex_cat, local = FALSE, country = country, year="latest")
```
[1] NA

**Comment by gaborcsardi** [comment]
Hi, this is a read only mirror of CRAN, please see the package authors in the `DESCRIPTION` file. Look for `Maintainer`, `BugReports` and `URL`. Thanks!
